name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    
  workflow_dispatch:
      inputs:
        version:
          type: string
          required: true
          description: App build version

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    env:
      IMG_LABEL: $(date +%s)
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      ORG: razorcorp

    steps:
      - uses: actions/checkout@v3
      - name: Checkout source
    
      - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      - name: Log in to Docker Hub
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
          
      - uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      - name: Build the Docker image
        with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            build-args: |
              VERSION="$IMG_LABEL"
              GOOS=linux
              GOARCH=amd64
              
#         run: docker build . \
#           --file Dockerfile \
#           --tag ghcr.io/razorcorp/bfc-bin-collection-notifier:$IMG_LABEL \
#           --build-arg VERSION="$IMG_LABEL" \
#           --build-arg GOOS=linux \
#           --build-arg GOARCH=amd64
